server {
    listen 80;
    server_name _;

    location / {
        root  /usr/share/nginx/html;
        index index.html;
    }

    # Gebruikt door de ALB health check en de CodeDeploy Blue/Green health check
    location = /healthz {
        root /usr/share/nginx/html;
    }

    # Gebruikt door de nginx-prometheus-exporter sidecar (poort 9113)
    location = /nginx_status {
        stub_status on;
        allow all;
    }
}
