name: Terraform IaC Pipeline

on:
  pull_request:
    branches: [main]
    paths: ["**/*.tf"]
  push:
    branches: [main]
    paths: ["**/*.tf"]

# Nodig voor AWS OIDC authenticatie
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1

jobs:
  plan:
    name: Terraform Plan
    runs-on: [self-hosted, aws, innovatech-webplatform]

    steps:
      - uses: actions/checkout@v4

      # Stap toevoegen als je runner geen IAM Instance Profile gebruikt:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Terraform fmt check
        run: terraform fmt -check

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ vars.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE }}"

      - run: terraform validate

      - name: Terraform plan
        run: |
          terraform plan -no-color -out=tfplan \
            -var="github_org=${{ github.repository_owner }}" \
            -var="github_repo=${{ github.event.repository.name }}" \
            -var="github_runner_token=${{ secrets.GH_RUNNER_REG_TOKEN }}"

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: tfplan
          retention-days: 14

  apply:
    name: Terraform Apply
    needs: plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: [self-hosted, aws, innovatech-webplatform]
    environment: production

    steps:
      - uses: actions/checkout@v4

      # Stap toevoegen als je runner geen IAM Instance Profile gebruikt:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ vars.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE }}"

      - uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ github.sha }}

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
